### ISSUE TITLE
OOM when allocating tensor with shape[1024,50799]

### ISSUE THREAD

**Issue by alialrabi** [bshao001/ChatLearner#30]
I'm trying to get chatbot to run with ec2 instance( by g2.2xlarge) but get this error
  
Training loop started @ 2018-01-27 11:28:24
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1024,50799]
	 [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape)]]
	 [[Node: gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2653_gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Neg/StackPopV2/_35)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bottrainer.py", line 142, in <module>
    bt.train(res_dir)
  File "bottrainer.py", line 71, in train
    step_result = self.model.train_step(sess, learning_rate=learning_rate)
  File "/home/ubuntu/ChatLearner/chatbot/modelcreator.py", line 122, in train_step
    feed_dict={self.learning_rate: learning_rate})
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1024,50799]
	 [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape)]]
	 [[Node: gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2653_gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Neg/StackPopV2/_35)]]

Caused by op 'gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1', defined at:
  File "bottrainer.py", line 141, in <module>
    bt = BotTrainer(corpus_dir=corp_dir)
  File "bottrainer.py", line 35, in __init__
    batch_input=self.train_batch)
  File "/home/ubuntu/ChatLearner/chatbot/modelcreator.py", line 86, in __init__
    gradients = tf.gradients(self.train_loss, params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 922, in _MatMulGrad
    grad_b = math_ops.matmul(a, grad, transpose_a=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2437, in _mat_mul
    name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul', defined at:
  File "bottrainer.py", line 141, in <module>
    bt = BotTrainer(corpus_dir=corp_dir)
[elided 0 identical lines from previous traceback]
  File "bottrainer.py", line 35, in __init__
    batch_input=self.train_batch)
  File "/home/ubuntu/ChatLearner/chatbot/modelcreator.py", line 65, in __init__
    res = self.build_graph(hparams, scope=scope)
  File "/home/ubuntu/ChatLearner/chatbot/modelcreator.py", line 134, in build_graph
    encoder_outputs, encoder_state, hparams)
  File "/home/ubuntu/ChatLearner/chatbot/modelcreator.py", line 221, in _build_decoder
    logits = self.output_layer(outputs.rnn_output)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 156, in call
    [0]])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2520, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2437, in _mat_mul
    name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1024,50799]
	 [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape)]]
	 [[Node: gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape/_331 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2653_gradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_0/dropout/div_grad/Neg/StackPopV2/_35)]]

**Comment by alialrabi** [comment]
It works after change batch_size to 64, 128 get same error,What is the best ec2 instance type do you think should works fine.Form this output data ,Is it work with gpu oor cpu?I see both

Thanks for you time and great  example.

**Comment by bshao001** [comment]
@alialrabi 
I have no idea about the memory size of your GPU. But mine was based on the memory of 22 GB. You can probably figure out a good size based on the ratio. BTW, if you think this project or my time is helpful to you, please consider starring and/or forking my project, if you could. Thank you!
